### PR TITLE
Jupyter notebook & Matlab scripts

### PR DESCRIPTION
**Pull request by karandahele**
- Added Jupyter notebook for mining xml files, and converting to feature checklist for ML
- Uploaded Matlab scripts for extracting text from structured PDFs

### CODE REVIEW

**Review by thenineteen — APPROVED** [review]
deleted local forked semiology_dictionary copy - was out of date. Can use the one under NLP/tests instead if required.

**Comment by thenineteen** [comment]
Thanks!

**Comment by thenineteen** [comment]
why the hasthag # 5?

**Comment by thenineteen** [comment]
could you also clarify where the jupyter notebook is that runs the entire set?

**Comment by karandahele** [comment]
The notebook is here: Epilepsy-Repository/preprocessing/mine_xml_records_kd.ipynb

Sure, I can rerun it with the new yaml file.

**Comment by thenineteen** [comment]
No need to run with new yaml - for future runs with more features.

let me know when you have the DataFrame!

**Pull request merged**
